server:
  servlet:
    context-path: /auth
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123